version: '3.8'

services:
  pansou-search:
    image: virking/pansou-cloud189
    ports:
      - "15000:5000"
    container_name: pansou-search
    restart: unless-stopped
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - SEARCH_API_URL=#fish2018/pansou的部署地址
      - ADD_API_URL= #cloudpan189-shared的部署地址
      - USERNAME= #cloudpan189-shared的用户名
      - PASSWORD= #cloudpan189-shared的密码
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
